run:
  timeout: 15m
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: false
output:
  formats:
    - format: colored-line-number
linters-settings:
  gofmt:
    simplify: true
linters:
  disable-all: true
  enable:
    - importas
    - errcheck
    - gosimple
    - govet
    - godot
    - ineffassign
    - staticcheck
    - unused
    - containedctx
    - contextcheck
    - nilnil
    - nilerr
    - gci
    - asciicheck
    - unconvert
    - loggercheck
    - copyloopvar
    - asasalint
    - durationcheck
    - makezero
    - reassign
    - revive
issues:
  fix: false
  exclude-rules:
    - path: _test\.go$
      linters:
        - gosec