// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: UserDataStorage)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserDataStorage is a mock of UserDataStorage interface.
type MockUserDataStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataStorageMockRecorder
}

// MockUserDataStorageMockRecorder is the mock recorder for MockUserDataStorage.
type MockUserDataStorageMockRecorder struct {
	mock *MockUserDataStorage
}

// NewMockUserDataStorage creates a new mock instance.
func NewMockUserDataStorage(ctrl *gomock.Controller) *MockUserDataStorage {
	mock := &MockUserDataStorage{ctrl: ctrl}
	mock.recorder = &MockUserDataStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataStorage) EXPECT() *MockUserDataStorageMockRecorder {
	return m.recorder
}

// AddUserData mocks base method.
func (m *MockUserDataStorage) AddUserData(arg0 int64, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserData indicates an expected call of AddUserData.
func (mr *MockUserDataStorageMockRecorder) AddUserData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserData", reflect.TypeOf((*MockUserDataStorage)(nil).AddUserData), arg0, arg1, arg2)
}

// ClearUserData mocks base method.
func (m *MockUserDataStorage) ClearUserData(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearUserData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearUserData indicates an expected call of ClearUserData.
func (mr *MockUserDataStorageMockRecorder) ClearUserData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearUserData", reflect.TypeOf((*MockUserDataStorage)(nil).ClearUserData), arg0)
}

// GetUserData mocks base method.
func (m *MockUserDataStorage) GetUserData(arg0 int64, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserData", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockUserDataStorageMockRecorder) GetUserData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserData", reflect.TypeOf((*MockUserDataStorage)(nil).GetUserData), arg0, arg1)
}
