// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: UserDataStorage)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/mrkovshik/fortune_teller_bot/internal/config"
)

// MockUserDataStorage is a mock of UserDataStorage interface.
type MockUserDataStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataStorageMockRecorder
}

// MockUserDataStorageMockRecorder is the mock recorder for MockUserDataStorage.
type MockUserDataStorageMockRecorder struct {
	mock *MockUserDataStorage
}

// NewMockUserDataStorage creates a new mock instance.
func NewMockUserDataStorage(ctrl *gomock.Controller) *MockUserDataStorage {
	mock := &MockUserDataStorage{ctrl: ctrl}
	mock.recorder = &MockUserDataStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataStorage) EXPECT() *MockUserDataStorageMockRecorder {
	return m.recorder
}

// GetBookID mocks base method.
func (m *MockUserDataStorage) GetBookID(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookID indicates an expected call of GetBookID.
func (mr *MockUserDataStorageMockRecorder) GetBookID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookID", reflect.TypeOf((*MockUserDataStorage)(nil).GetBookID), arg0, arg1)
}

// GetLanguage mocks base method.
func (m *MockUserDataStorage) GetLanguage(arg0 context.Context, arg1 int64) (config.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguage", arg0, arg1)
	ret0, _ := ret[0].(config.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguage indicates an expected call of GetLanguage.
func (mr *MockUserDataStorageMockRecorder) GetLanguage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguage", reflect.TypeOf((*MockUserDataStorage)(nil).GetLanguage), arg0, arg1)
}

// SaveBookID mocks base method.
func (m *MockUserDataStorage) SaveBookID(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBookID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBookID indicates an expected call of SaveBookID.
func (mr *MockUserDataStorageMockRecorder) SaveBookID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBookID", reflect.TypeOf((*MockUserDataStorage)(nil).SaveBookID), arg0, arg1, arg2)
}

// SaveLanguage mocks base method.
func (m *MockUserDataStorage) SaveLanguage(arg0 context.Context, arg1 int64, arg2 config.Language) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLanguage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLanguage indicates an expected call of SaveLanguage.
func (mr *MockUserDataStorageMockRecorder) SaveLanguage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLanguage", reflect.TypeOf((*MockUserDataStorage)(nil).SaveLanguage), arg0, arg1, arg2)
}
