// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: BookStorage)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBookStorage is a mock of BookStorage interface.
type MockBookStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBookStorageMockRecorder
}

// MockBookStorageMockRecorder is the mock recorder for MockBookStorage.
type MockBookStorageMockRecorder struct {
	mock *MockBookStorage
}

// NewMockBookStorage creates a new mock instance.
func NewMockBookStorage(ctrl *gomock.Controller) *MockBookStorage {
	mock := &MockBookStorage{ctrl: ctrl}
	mock.recorder = &MockBookStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookStorage) EXPECT() *MockBookStorageMockRecorder {
	return m.recorder
}

// GetRandomBookTitle mocks base method.
func (m *MockBookStorage) GetRandomBookTitle() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomBookTitle")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRandomBookTitle indicates an expected call of GetRandomBookTitle.
func (mr *MockBookStorageMockRecorder) GetRandomBookTitle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomBookTitle", reflect.TypeOf((*MockBookStorage)(nil).GetRandomBookTitle))
}

// GetRandomSentenceFromBook mocks base method.
func (m *MockBookStorage) GetRandomSentenceFromBook(arg0 string, arg1 int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomSentenceFromBook", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomSentenceFromBook indicates an expected call of GetRandomSentenceFromBook.
func (mr *MockBookStorageMockRecorder) GetRandomSentenceFromBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomSentenceFromBook", reflect.TypeOf((*MockBookStorage)(nil).GetRandomSentenceFromBook), arg0, arg1)
}

// ListBooks mocks base method.
func (m *MockBookStorage) ListBooks() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockBookStorageMockRecorder) ListBooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockBookStorage)(nil).ListBooks))
}
