// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: BookStorage)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	booksmeta "github.com/mrkovshik/fortune_teller_bot/internal/storage/books-meta"
)

// MockBookStorage is a mock of BookStorage interface.
type MockBookStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBookStorageMockRecorder
}

// MockBookStorageMockRecorder is the mock recorder for MockBookStorage.
type MockBookStorageMockRecorder struct {
	mock *MockBookStorage
}

// NewMockBookStorage creates a new mock instance.
func NewMockBookStorage(ctrl *gomock.Controller) *MockBookStorage {
	mock := &MockBookStorage{ctrl: ctrl}
	mock.recorder = &MockBookStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookStorage) EXPECT() *MockBookStorageMockRecorder {
	return m.recorder
}

// GetBookByID mocks base method.
func (m *MockBookStorage) GetBookByID(arg0 context.Context, arg1 int64) (*booksmeta.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByID", arg0, arg1)
	ret0, _ := ret[0].(*booksmeta.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID.
func (mr *MockBookStorageMockRecorder) GetBookByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockBookStorage)(nil).GetBookByID), arg0, arg1)
}

// GetRandomBook mocks base method.
func (m *MockBookStorage) GetRandomBook(arg0 context.Context, arg1 ...booksmeta.ListOption) (*booksmeta.Book, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRandomBook", varargs...)
	ret0, _ := ret[0].(*booksmeta.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomBook indicates an expected call of GetRandomBook.
func (mr *MockBookStorageMockRecorder) GetRandomBook(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomBook", reflect.TypeOf((*MockBookStorage)(nil).GetRandomBook), varargs...)
}

// ListBooks mocks base method.
func (m *MockBookStorage) ListBooks(arg0 context.Context, arg1 ...booksmeta.ListOption) ([]*booksmeta.Book, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBooks", varargs...)
	ret0, _ := ret[0].([]*booksmeta.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockBookStorageMockRecorder) ListBooks(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockBookStorage)(nil).ListBooks), varargs...)
}
