// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: StateStorage)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	statestorage "github.com/mrkovshik/fortune_teller_bot/internal/storage/statestorage"
)

// MockStateStorage is a mock of StateStorage interface.
type MockStateStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStateStorageMockRecorder
}

// MockStateStorageMockRecorder is the mock recorder for MockStateStorage.
type MockStateStorageMockRecorder struct {
	mock *MockStateStorage
}

// NewMockStateStorage creates a new mock instance.
func NewMockStateStorage(ctrl *gomock.Controller) *MockStateStorage {
	mock := &MockStateStorage{ctrl: ctrl}
	mock.recorder = &MockStateStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStorage) EXPECT() *MockStateStorageMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStateStorage) Add(arg0 int64, arg1 *statestorage.ChatState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", arg0, arg1)
}

// Add indicates an expected call of Add.
func (mr *MockStateStorageMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStateStorage)(nil).Add), arg0, arg1)
}

// Clear mocks base method.
func (m *MockStateStorage) Clear(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear", arg0)
}

// Clear indicates an expected call of Clear.
func (mr *MockStateStorageMockRecorder) Clear(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockStateStorage)(nil).Clear), arg0)
}

// Get mocks base method.
func (m *MockStateStorage) Get(arg0 int64) (*statestorage.ChatState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*statestorage.ChatState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateStorageMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStateStorage)(nil).Get), arg0)
}

// Update mocks base method.
func (m *MockStateStorage) Update(arg0 int64, arg1 *statestorage.ChatState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", arg0, arg1)
}

// Update indicates an expected call of Update.
func (mr *MockStateStorageMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStateStorage)(nil).Update), arg0, arg1)
}
