// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/storage/bookstorage (interfaces: TextParser)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTextParser is a mock of TextParser interface.
type MockTextParser struct {
	ctrl     *gomock.Controller
	recorder *MockTextParserMockRecorder
}

// MockTextParserMockRecorder is the mock recorder for MockTextParser.
type MockTextParserMockRecorder struct {
	mock *MockTextParser
}

// NewMockTextParser creates a new mock instance.
func NewMockTextParser(ctrl *gomock.Controller) *MockTextParser {
	mock := &MockTextParser{ctrl: ctrl}
	mock.recorder = &MockTextParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextParser) EXPECT() *MockTextParserMockRecorder {
	return m.recorder
}

// ParseRandomSentence mocks base method.
func (m *MockTextParser) ParseRandomSentence(arg0 []byte, arg1 int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRandomSentence", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRandomSentence indicates an expected call of ParseRandomSentence.
func (mr *MockTextParserMockRecorder) ParseRandomSentence(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRandomSentence", reflect.TypeOf((*MockTextParser)(nil).ParseRandomSentence), arg0, arg1)
}
