// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: StepStorage)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	steps "github.com/mrkovshik/fortune_teller_bot/internal/storage/steps"
)

// MockStepStorage is a mock of StepStorage interface.
type MockStepStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStepStorageMockRecorder
}

// MockStepStorageMockRecorder is the mock recorder for MockStepStorage.
type MockStepStorageMockRecorder struct {
	mock *MockStepStorage
}

// NewMockStepStorage creates a new mock instance.
func NewMockStepStorage(ctrl *gomock.Controller) *MockStepStorage {
	mock := &MockStepStorage{ctrl: ctrl}
	mock.recorder = &MockStepStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepStorage) EXPECT() *MockStepStorageMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockStepStorage) Clear(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear", arg0)
}

// Clear indicates an expected call of Clear.
func (mr *MockStepStorageMockRecorder) Clear(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockStepStorage)(nil).Clear), arg0)
}

// Peek mocks base method.
func (m *MockStepStorage) Peek(arg0 int64) (steps.ChatStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek", arg0)
	ret0, _ := ret[0].(steps.ChatStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Peek indicates an expected call of Peek.
func (mr *MockStepStorageMockRecorder) Peek(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockStepStorage)(nil).Peek), arg0)
}

// PeekPrevious mocks base method.
func (m *MockStepStorage) PeekPrevious(arg0 int64) (steps.ChatStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekPrevious", arg0)
	ret0, _ := ret[0].(steps.ChatStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PeekPrevious indicates an expected call of PeekPrevious.
func (mr *MockStepStorageMockRecorder) PeekPrevious(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekPrevious", reflect.TypeOf((*MockStepStorage)(nil).PeekPrevious), arg0)
}

// Push mocks base method.
func (m *MockStepStorage) Push(arg0 int64, arg1 steps.ChatStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockStepStorageMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockStepStorage)(nil).Push), arg0, arg1)
}
