// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrkovshik/fortune_teller_bot/internal/updateprocessor (interfaces: UpdateProcessor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/mrkovshik/fortune_teller_bot/internal/model"
)

// MockUpdateProcessor is a mock of UpdateProcessor interface.
type MockUpdateProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateProcessorMockRecorder
}

// MockUpdateProcessorMockRecorder is the mock recorder for MockUpdateProcessor.
type MockUpdateProcessorMockRecorder struct {
	mock *MockUpdateProcessor
}

// NewMockUpdateProcessor creates a new mock instance.
func NewMockUpdateProcessor(ctrl *gomock.Controller) *MockUpdateProcessor {
	mock := &MockUpdateProcessor{ctrl: ctrl}
	mock.recorder = &MockUpdateProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateProcessor) EXPECT() *MockUpdateProcessorMockRecorder {
	return m.recorder
}

// ProcessCallback mocks base method.
func (m *MockUpdateProcessor) ProcessCallback(arg0 context.Context, arg1 *model.CallbackQuery) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessCallback", arg0, arg1)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessCallback indicates an expected call of ProcessCallback.
func (mr *MockUpdateProcessorMockRecorder) ProcessCallback(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessCallback", reflect.TypeOf((*MockUpdateProcessor)(nil).ProcessCallback), arg0, arg1)
}

// ProcessMessage mocks base method.
func (m *MockUpdateProcessor) ProcessMessage(arg0 context.Context, arg1 *model.Message) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMessage", arg0, arg1)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessMessage indicates an expected call of ProcessMessage.
func (mr *MockUpdateProcessorMockRecorder) ProcessMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMessage", reflect.TypeOf((*MockUpdateProcessor)(nil).ProcessMessage), arg0, arg1)
}
